src/main/java/com/proambiente/webapp/controller/PrincipalBean.java
package com.proambiente.webapp.controller;


import java.io.Serializable;
import java.util.logging.Logger;

import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.proambiente.modelo.Usuario;
import com.proambiente.webapp.service.FechaService;

/**
 * Clase de utilidad para implementar el cierre de sesion de la aplicacion
 * @author FABIAN
 */


@Named
@SessionScoped
public class PrincipalBean implements Serializable {
	
	@Inject FechaService fechaService;
	
	
	
	@Inject PrincipalService principalService;
	
	
	
	private static final Logger logger = Logger.getLogger(PrincipalBean.class
			.getName());
	private static final long serialVersionUID = 1L;

	public String getUsuarioAutenticado(){
		
		return principalService.getNombreUsuarioSession();
	}
	
	public String getNombresApellidosUsuario() {
		Usuario usuario = principalService.getUsuarioAutenticado();
		if(usuario == null) {
			return "";
		}else {
			return usuario.getNombres() + " " + usuario.getApellidos(); 
		}
	}
	
	

}

src/main/webapp/WEB-INF/templates/breadcrumb.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pa="http://primefaces.org/mirage"
	xmlns:o="http://omnifaces.org/ui">

	<div class="layout-breadcrumb">
		<div class="breadcrumb">
			<div class="route-bar-breadcrumb">
				<ui:insert name="viewname" />
			</div>
		</div>
		<h:form id="formbc">
		<div class="notification" id="notificacionbc">
			<span>#{ultimaAlertaBean.ultimaAlerta.descripcion}</span>
			<span>#{ultimaAlertaBean.ultimaAlerta.fecha}</span>
		</div>
		
		<p:poll interval="60" listener="#{ultimaAlertaBean.consultarAlertas(e)}" update="@form"/>
		</h:form>
	</div>

</ui:composition>

src/main/webapp/WEB-INF/templates/config.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <div id="layout-config" class="layout-config">

        <a href="#" id="layout-config-button" class="layout-config-button">
            <i class="pi pi-cog"/>
        </a>

        <a href="#" id="layout-config-close" class="layout-config-close">
            <i class="pi pi-times"/>
        </a>

        <div class="layout-config-content">
            <h:form id="config-form">
                <h5 style="margin-top: 0;">Menu Type</h5>
                <p:selectOneRadio value="#{guestPreferences.horizontalMenu}" layout="responsive" columns="2">
                    <f:selectItem itemLabel="Overlay" itemValue="false" />
                    <f:selectItem itemLabel="Horizontal" itemValue="true" />
                    <p:ajax listener="#{guestPreferences.onMenuTypeChange}" process="@this" update=":config-form menuform"/>
                </p:selectOneRadio>

                <h5>Color Scheme</h5>
                <p:selectOneRadio value="#{guestPreferences.darkMode}" layout="responsive" columns="2">
                    <f:selectItem itemLabel="Light" itemValue="false" />
                    <f:selectItem itemLabel="Dark" itemValue="true" />
                    <p:ajax onstart="PrimeFaces.MirageConfigurator.beforeResourceChange()"
                            listener="#{guestPreferences.onColorSchemeChange}" process="@this" update=":config-form" />
                </p:selectOneRadio>

                <h5>Input Style</h5>
                <p:selectOneRadio value="#{guestPreferences.inputStyle}" layout="responsive" columns="2"
                                  onchange="PrimeFaces.MirageConfigurator.updateInputStyle(event.target.value)">
                    <f:selectItem itemLabel="Outlined" itemValue="outlined" />
                    <f:selectItem itemLabel="Filled" itemValue="filled" />
                </p:selectOneRadio>

                <h5>Menu Colors</h5>
                <p:selectOneRadio value="#{guestPreferences.menuColor}"  layout="responsive" columns="2">
                    <f:selectItem itemLabel="Light" itemValue="light" />
                    <f:selectItem itemLabel="Dark" itemValue="dark" />
                    <f:selectItem itemLabel="Custom" itemValue="custom" />
                    <p:ajax onstart="PrimeFaces.MirageConfigurator.beforeResourceChange()" listener="#{guestPreferences.onMenuColorChange()}" update=":config-form"/>
                </p:selectOneRadio>

                <p:outputPanel id="menucolors-panel">
                    <div class="layout-themes">
                        <ui:repeat value="#{guestPreferences.menuColors.get(guestPreferences.menuColor)}" var="menuColor">
                            <div>
                                <p:commandLink actionListener="#{guestPreferences.setMenuTheme(menuColor.file)}"
                                               style="background-color: #{menuColor.color}" title="#{menuColor.name}"
                                               process="@this" update=":config-form"
                                               onstart="PrimeFaces.MirageConfigurator.beforeResourceChange()"
                                               oncomplete="PrimeFaces.MirageConfigurator.changeMenuTheme('#{guestPreferences.menuColor}', '#{menuColor.file}', #{guestPreferences.darkMode})">
                                    <p:graphicImage name="images/configurator/menu/theme/#{menuColor.color}"
                                                    library="mirage-layout" title="#{menuColor.name}"
                                                    style="height: 100%; width: 100%;"
                                                    rendered="#{guestPreferences.menuColor eq 'custom'}"/>
                                    <ui:fragment rendered="#{menuColor.file eq guestPreferences.menuTheme}">
                                        <i class="pi pi-check"/>
                                    </ui:fragment>
                                </p:commandLink>
                            </div>
                        </ui:repeat>
                    </div>
                </p:outputPanel>

                <h5>Themes</h5>
                <p:outputPanel id="componentThemes-panel">
                    <div class="layout-themes">
                        <ui:repeat value="#{guestPreferences.componentThemes}" var="componentTheme">
                            <div>
                                <p:commandLink actionListener="#{guestPreferences.setComponentTheme(componentTheme.file)}"
                                               style="background-color: #{componentTheme.color}"
                                               process="@this" update=":config-form"
                                               onstart="PrimeFaces.MirageConfigurator.beforeResourceChange()"
                                               oncomplete="PrimeFaces.MirageConfigurator.changeComponentsTheme('#{componentTheme.file}', #{guestPreferences.darkMode})">
                                    <ui:fragment rendered="#{componentTheme.file eq guestPreferences.componentTheme}">
                                        <i class="pi pi-check"/>
                                    </ui:fragment>
                                </p:commandLink>
                            </div>
                        </ui:repeat>
                    </div>
                </p:outputPanel>

            </h:form>

        </div>

    </div>
</ui:composition>

src/main/webapp/WEB-INF/templates/default.xhtml
<!--
    JBoss, Home of Professional Open Source
    Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>${artifactId}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <h:outputStylesheet name="css/screen.css" />
</h:head>
<h:body>
    <div id="container">
        <div class="dualbrand">
            <img src="resources/gfx/dualbrand_logo.png" />
        </div>
        <div id="content">
            <ui:insert name="content">
                    [Template content will be inserted here]
         </ui:insert>
        </div>
        <div id="aside">
            <p>Learn more about JBoss Enterprise Application
                Platform 6.</p>
            <ul>
                <li><a href="https://access.redhat.com/knowledge/docs/JBoss_Enterprise_Application_Platform/">Documentation</a></li>
                <li><a href="http://red.ht/jbeap-6">Product Information</a></li>
            </ul>
            <p>Learn more about JBoss AS 7.</p>
            <ul>
                <li><a
                    href="http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart/guide/Introduction">Getting
                        Started Developing Applications Guide</a></li>
                <li><a href="http://jboss.org/jbossas">Community
                        Project Information</a></li>
            </ul>
        </div>
        <div id="footer">
            <p>
                This project was generated from a Maven archetype from
                JBoss.<br />
            </p>
        </div>
    </div>
</h:body>
</html>

src/main/webapp/WEB-INF/templates/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <div class="layout-footer">
        <div class="logo-text">
            <p:graphicImage name="images/icono_escritorio_prortm.png" library="mirage-layout" />
            <div class="text">
                <h1>Pro-ambiente sas 2023</h1>
                <span>Prortm </span>
                <span>#{informacionCdaSessionBean.versionSoftware}</span>
            </div>
        </div>
        <div class="icons">
            <div class="icon icon-hastag">
                <a href="https://www.proambientesas.com" class="pi pi-home"/>
            </div>            
        </div>
    </div>
</ui:composition>

src/main/webapp/WEB-INF/templates/rightpanel.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:pa="http://primefaces.org/mirage">

    <div class="layout-rightpanel">
        <div class="right-panel-header">
            <div class="title">
                <span>Hoy</span>
                <h1>#{fechaBean.getFechaHoraActual()}</h1>
            </div>
            <a href="#" class="rightpanel-exit-button">
                <i class="pi pi-times"/>
            </a>
        </div>
        <div class="right-panel-content">
            <h:form>
                <div class="right-panel-content-row">                      
				</div>
                <div class="right-panel-content-row">
                    <div class="calendar">
                        <h1>Calendar</h1>
                        <p:calendar mode="inline" />
                    </div>
                </div>

                
            </h:form>
        </div>
    </div>

</ui:composition>

src/main/webapp/WEB-INF/templates/sidebar.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pm="http://primefaces.org/mirage">

    <div class="layout-sidebar">
        <div class="sidebar-logo">
            <a href="#" class="sidebar-pin" title="Toggle Menu">
                <i class="pi pi-lock"/>
            </a>
            <a href="/prortmwebapp/inicio.xhtml">
                <p:graphicImage name="images/logo_web.png" library="mirage-layout" />
                <span class="app-name">PRORTM</span>
            </a>
        </div>

        <div class="layout-menu-container">
            <h:form id="menuform">
                <pm:menu>
                    <p:submenu label="REVISION">
							<p:menuitem value="Habilitacion Rapida revision"
								url="/prortmwebapp/pages/ingresorapido.xhtml?faces-redirect=true" ajax="false" />
							<p:menuitem value="Buscar Por Placa"
								url="/prortmwebapp/pages/revisionplaca.xhtml?faces-redirect=true"
								ajax="false" />
							<p:menuitem value="Estado Revisiones" url="/prortmwebapp/estadorevisiones.xhtml?faces-redirect=true"
								ajax="false" />
							<p:menuitem value="Resumen por fecha" url="/prortmwebapp/pages/resumen.xhtml?faces-redirect=true"
								ajax="false" />
							<p:menuitem value="Importar Datos" url="/prortmwebapp/pages/importardesdeexcel.xhtml?faces-redirect=true"
								ajax="false" />
							<p:menuitem value="Anular Revision"
								url="/prortmwebapp/pages/borrarrevision.xhtml?faces-redirect=true" ajax="false" />
								<p:menuitem value="Inicio"
								url="/prortmwebapp/inicio.xhtml" ajax="false" />
								
							<p:menuitem value="Datos Revision" url="/prortmwebapp/pages/revisiones.xhtml?faces-redirect=true"
								ajax="false" />
								
						</p:submenu>

						<p:submenu label="Configuracion">
							<p:menuitem value="Usuarios" url="/prortmwebapp/pages/usuarios.xhtml?faces-redirect=true" />
							<p:menuitem value="Informacion Cda"
								url="/prortmwebapp/pages/configuracion.xhtml?faces-redirect=true" ajax="false"/>
							<p:menuitem value="Crear aseguradora"
								url="/prortmwebapp/pages/aseguradora.xhtml" />
							<p:menuitem value="Analizadores" url="/prortmwebapp/pages/analizador.xhtml?faces-redirect=true" />
							<p:menuitem value="Equipos" url="/prortmwebapp/pages/equipos.xhtml?faces-redirect=true" />
							<p:menuitem value="Filtros" url="/prortmwebapp/pages/filtros.xhtml?faces-redirect=true" />
							<p:menuitem value="Pipetas" url="/prortmwebapp/pages/pipetas.xhtml?faces-redirect=true" />
							<p:menuitem value="Pistas" url="/prortmwebapp/pages/pistas.xhtml?faces-redirect=true" />
							<p:menuitem value="Gestion Logo Onac" url="/prortmwebapp/pages/logosonac.xhtml?faces-redirect=true" />							
							<p:menuitem value="Configuracion Taximetro"
								url="/prortmwebapp/pages/parametrospruebataximetro.xhtml?faces-redirect=true" />
							<p:menuitem value="Cambiar password"
								url="/prortmwebapp/pages/cambiopassword.xhtml" />
							<p:menuitem value="Importar Colores"
								url="/prortmwebapp/pages/importarcolores.xhtml?faces-redirect=true" />
							<p:menuitem value="Importar Marcas"
								url="/prortmwebapp/pages/importarmarcas.xhtml?faces-redirect=true" />
							<p:menuitem value="Importar Lineas"
								url="/prortmwebapp/pages/importarlineas.xhtml?faces-redirect=true" />
								
							<p:menuitem value="Historial Cambio Password"
								url="/prortmwebapp/pages/historialcambiopassword.xhtml?faces-redirect=true" />	
								
						</p:submenu>
						
						<p:submenu label = "Bitacora">
							<p:menuitem value="Ingreso Errores"
								url="/prortmwebapp/pages/bitacora.xhtml?faces-redirect=true" />
							<p:menuitem value="Ver Eventos"
								url="/prortmwebapp/pages/entradasbitacora.xhtml?faces-redirect=true" />
						</p:submenu>	
						
						
						<p:submenu label="Historial inspecciones">
							<p:menuitem value="Inspecciones vehiculo"
								url="/prortmwebapp/pages/inspeccion.xhtml"></p:menuitem>
							<p:menuitem value="Informe Sensorial"
								url="/prortmwebapp/pages/informeinspeccionsensorial.xhtml?faces-redirect=true"></p:menuitem>
							<p:menuitem value="Borrar Inspeccion"
								url="/prortmwebapp/pages/borrarinspeccion.xhtml?faces-redirect=true"></p:menuitem>
						</p:submenu>
						<p:submenu label="Envios Sicov">
							<p:menuitem value="Eco" url="/prortmwebapp/pages/testechoci2.xhtml?faces-redirect=true"
								ajax="false"></p:menuitem>							
							<p:menuitem value="Alertas"
								url="/prortmwebapp/pages/alertas.xhtml"></p:menuitem>
								
							<p:menuitem value="Segundo envio "
								url="/prortmwebapp/pages/segundoenvioindra.xhtml"></p:menuitem>	
							<p:menuitem value="Registrar 1 envio manualmente"
								url="/prortmwebapp/pages/registrarprimerenvio.xhtml"></p:menuitem>
							<p:menuitem value="Lista Revisiones En Proceso"
								url="/prortmwebapp/pages/listaenviosenproceso.xhtml"></p:menuitem>
						</p:submenu>

						<p:submenu label="Ambiental">
							<p:submenu label="Car Cundinamarca">
								<p:menuitem value="Pruebas Diesel Car Cundinamarca"
									url="/prortmwebapp/pages/pruebasdieselcarcundinamarca.xhtml"></p:menuitem>

								<p:menuitem value="Pruebas Otto Car Cundinamarca"
									url="/prortmwebapp/pages/pruebasottocarcundinamarca.xhtml"></p:menuitem>
								
								<p:menuitem value="Pruebas Otto Motos Car Cundinamarca"
								url="/prortmwebapp/pages/pruebasottomotocicletacarcundinamarca.xhtml"></p:menuitem>
								
							</p:submenu>
							<p:submenu label = "Caldas">
								<p:menuitem value="Informe ambiental"
											url="/prortmwebapp/pages/pruebasottomotocicletadieselcaldas.xhtml">
									
								</p:menuitem>
							</p:submenu>
							<p:submenu label = "Medellin">
								<p:menuitem value="Informe Revisiones"
											url="/prortmwebapp/pages/informerevisionesmedellin.xhtml">
							    </p:menuitem>
								<p:menuitem value="Informe Medidas "
											url="/prortmwebapp/pages/pruebasottomotocicletamedellin.xhtml">
											
									
								</p:menuitem>
								
								<p:menuitem value="Informe Diesel Res 0762 "
											url="/prortmwebapp/pages/pruebasdieselres0762medellin.xhtml">								
								</p:menuitem>
								
								<p:menuitem value="Informe Motocicletas Res 0762 "
											url="/prortmwebapp/pages/pruebasottomotocicletares0762.xhtml">								
								</p:menuitem>
								
								<p:menuitem value="Informe Vehiculos Res 0762 "
											url="/prortmwebapp/pages/pruebasottovehiculos0762.xhtml">								
								</p:menuitem>
								
								
								
							</p:submenu>
							
							
							
							<p:menuitem value="Verificaciones Otto"
								url="/prortmwebapp/pages/verificacionesgasolina.xhtml?faces-redirect=true"></p:menuitem>
							
							<p:menuitem value="Verificaciones Linealidad"
								url="/prortmwebapp/pages/verificacioneslinealidad.xhtml?faces-redirect=true"></p:menuitem>
							<p:menuitem value="Prueba de Fugas"
								url="/prortmwebapp/pages/informepruebafugas.xhtml?faces-redirect=true"></p:menuitem>
							<p:menuitem value="Pruebas Otto Vehiculos"
								url="/prortmwebapp/pages/pruebasotto.xhtml"></p:menuitem>
							<p:menuitem value="Pruebas Otto Motocicletas"
								url="/prortmwebapp/pages/pruebasottomotocicleta.xhtml"></p:menuitem>							
							<p:menuitem value="Pruebas Diesel"
								url="/prortmwebapp/pages/pruebasdiesel.xhtml"></p:menuitem>		
							<p:menuitem value="Pruebas Ruido" url="/prortmwebapp/pages/pruebasruido.xhtml"></p:menuitem>
							
							<p:menuitem value="Informe" url="/prortmwebapp/pages/informesuper.xhtml"></p:menuitem>
							<p:menuitem value="Pruebas Abortads"
								url="/prortmwebapp/pages/pruebasabortadas.xhtml?faces-redirect=true"></p:menuitem>
							
						</p:submenu>
                </pm:menu>
            </h:form>
        </div>
    </div>

</ui:composition>

src/main/webapp/WEB-INF/templates/topbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui" xmlns:pa="http://primefaces.org/mirage"
                xmlns:o="http://omnifaces.org/ui">
	
	<o:socket channel="notify_secondary" 
			onmessage="someCommandScript" />
		<h:form id="form_notificacion" >
		<p:growl id= "growl_notificacion"></p:growl>
			<o:commandScript name="someCommandScript" action="#{notificacionBean.pushed(message)}"
				render=":form_notificacion:growl_notificacion" />
		</h:form>
	
    <div class="layout-topbar">
        <div class="layout-topbar-wrapper">
            <div class="layout-topbar-left">
                <div class="layout-topbar-logo-wrapper">
                    <a href="inicio.xhtml" class="layout-topbar-logo">
                        <p:graphicImage name="images/usuario.png" library="mirage-layout" />
                        <span class="app-name">Webapp</span>
                    </a>
                </div>

               




                <!-- Mega Menu -->

            </div>
            <div class="layout-topbar-right">
                <ul class="layout-topbar-actions">
                    
                    <li class="topbar-item">
                        <a href="/prortmwebapp/estadorevisiones.xhtml">
                            <i class="pi pi-filter"/>
                        </a>                        
                    </li>
                    <li class="topbar-item">
                        <a href="/prortmwebapp/pages/revisionplaca.xhtml">
                            <i class="pi pi-search"/>
                        </a>
                     </li>   
                    <li class="topbar-item">
                        <a href="/prortmwebapp/pages/ingresorapido.xhtml">
                            <i class="pi pi-car"/>
                        </a>
                        
                    </li>
                    <li class="topbar-item profile-item">
                        <a href="#">
                            <span class="profile-image-wrapper">
                                <p:graphicImage name="images/topbar/usuario.png" library="mirage-layout" />
                            </span>
                            <span class="profile-info-wrapper">
                                <h:outputText value="#{principalBean.usuarioAutenticado}"/>
                                <span></span>
                            </span>
                        </a>
                        <ul class="profile-item-submenu">
                            <li class="profile-submenu-header">
                                
                                <div class="profile">
                                    <p:graphicImage name="images/topbar/usuario.png" library="mirage-layout"
                                        width="40" />
                                    <h:outputText value="#{principalBean.nombresApellidosUsuario}"/>
                                    <span></span>
                                </div>
                            </li>
  


                            <li class="layout-submenu-footer">
                                <h:form>
                                <p:commandButton class="signout-button" action="#{logoutBean.logout}" ajax="false" value="Salir" ></p:commandButton>
                                </h:form>
                                
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="layout-rightpanel-button">
                            <i class="pi pi-arrow-left"/>
                        </a>
                    </li>
                </ul>

                <ul class="profile-mobile-wrapper">
                    <li class="topbar-item profile-item">
                        <a href="#">
                            <span class="profile-image-wrapper">
                                <p:graphicImage name="images/topbar/avatar-eklund.png" library="mirage-layout" />
                            </span>
                            <span class="profile-info-wrapper">
                                <h3>Olivia Eklund</h3>
                                <span>Design</span>
                            </span>
                        </a>
                        <ul>
                            <li class="profile-submenu-header">
                                <div class="performance">
                                    <span>Weekly Performance</span>
                                    <p:graphicImage name="images/topbar/asset-bars.svg" library="mirage-layout" />
                                </div>
                                <div class="profile">
                                    <p:graphicImage name="images/topbar/avatar-eklund.png" library="mirage-layout"
                                        width="45" />
                                    <h1>Olivia Eklund</h1>
                                    <span>Design</span>
                                </div>
                            </li>
                            <li>
                                <i class="pi pi-list icon icon-1"/>
                                <div class="menu-text">
                                    <p>Tasks</p>
                                    <span>3 open issues</span>
                                </div>
                                <i class="pi pi-angle-right"/>
                            </li>
                            <li>
                                <i class="pi pi-shopping-cart icon icon-2"/>
                                <div class="menu-text">
                                    <p>Payments</p>
                                    <span>24 new</span>
                                </div>
                                <i class="pi pi-angle-right"/>
                            </li>
                            <li>
                                <i class="pi pi-users icon icon-3"/>
                                <div class="menu-text">
                                    <p>Clients</p>
                                    <span>+80%</span>
                                </div>
                                <i class="pi pi-angle-right"/>
                            </li>
                            <li class="layout-submenu-footer">
                                <button class="signout-button">Sign Out</button>
                                <button class="buy-mirage-button">Buy Mirage</button>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</ui:composition>